[tool.poetry]
name = "matrixxx"
packages = ["{include : "src"}"]
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "3.0.1"

[tool.poetry.scripts]
app = "matrix.app:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
